//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Cars
    {
        public System.Guid ID { get; set; }
        public string FlatNumber { get; set; }
        public Nullable<int> Year { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public string Manifacture { get; set; }
        public string Type { get; set; }
        public string Purpose { get; set; }
        public string RegisterNumber { get; set; }
        public string SureName { get; set; }
        public string Name { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber3 { get; set; }
        public string PhoneNumber4 { get; set; }
        public string PhoneNumber5 { get; set; }
        public string PhoneNumber6 { get; set; }
        public string PhoneNumber7 { get; set; }
        public string PhoneNumber8 { get; set; }
    }
}
