//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_SumDuureg
    {
        public System.Guid ID { get; set; }
        public Nullable<int> ID_FLOAT { get; set; }
        public Nullable<int> IDNUM { get; set; }
        public Nullable<int> FullID { get; set; }
        public Nullable<int> FullID2 { get; set; }
        public string Name { get; set; }
        public Nullable<int> AimagID { get; set; }
    }
}
