//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUserToSystemUser
    {
        public System.Guid ID { get; set; }
        public string AspNetUserID { get; set; }
        public Nullable<System.Guid> SystemPersonID { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
    }
}
