//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Messenger_Messages
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> ConversationID { get; set; }
        public string MessageID { get; set; }
        public string FromID { get; set; }
        public string FromName { get; set; }
        public string FromEmail { get; set; }
        public string ToID { get; set; }
        public string ToName { get; set; }
        public string ToEmail { get; set; }
        public string Tag1 { get; set; }
        public string Tag2 { get; set; }
        public string Tag3 { get; set; }
        public string Tag4 { get; set; }
        public string ShareID { get; set; }
        public string ShareLink { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> Created_time { get; set; }
    }
}
