//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Accounts_Confirmed
    {
        public System.Guid ID { get; set; }
        public string AccountID { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsReal { get; set; }
    }
}
