//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Posts
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PageID { get; set; }
        public Nullable<System.Guid> GroupID { get; set; }
        public string PostID { get; set; }
        public string FromID { get; set; }
        public string FromName { get; set; }
        public string Message { get; set; }
        public string Story { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public Nullable<int> SharedCount { get; set; }
        public string PermalinkUrl { get; set; }
        public string Caption { get; set; }
        public string Description { get; set; }
        public string FullPicture { get; set; }
        public string Link { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public string Icon { get; set; }
        public string ObjectID { get; set; }
        public string ParentID { get; set; }
        public string SearchKey { get; set; }
    }
}
