//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Messenger_Conversations
    {
        public System.Guid ID { get; set; }
        public string ConversationID { get; set; }
        public Nullable<bool> Can_reply { get; set; }
        public Nullable<bool> Is_subscribed { get; set; }
        public Nullable<int> MessageCount { get; set; }
        public string link { get; set; }
        public string Sender1_ID { get; set; }
        public string Sender1_Name { get; set; }
        public string Sender1_Email { get; set; }
        public string Sender2_ID { get; set; }
        public string Sender2_Name { get; set; }
        public string Sender2_Email { get; set; }
        public string Sender3_ID { get; set; }
        public string Sender3_Name { get; set; }
        public string Sender3_Email { get; set; }
        public string Snippet { get; set; }
        public Nullable<int> Unread_count { get; set; }
        public Nullable<System.DateTime> Updated_time { get; set; }
        public string Participant1_ID { get; set; }
        public string Participant1_Name { get; set; }
        public string Participant1_Email { get; set; }
        public string Participant2_ID { get; set; }
        public string Participant2_Name { get; set; }
        public string Participant2_Email { get; set; }
        public string Participant3_ID { get; set; }
        public string Participant3_Name { get; set; }
        public string Participant3_Email { get; set; }
    }
}
