//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Post_Comment_Write_Keys
    {
        public System.Guid ID { get; set; }
        public string Key { get; set; }
        public string Condition { get; set; }
        public Nullable<System.Guid> WriteID { get; set; }
        public string Scope { get; set; }
    }
}
