//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Accounts_Crawler
    {
        public System.Guid ID { get; set; }
        public string GroupURL { get; set; }
        public string ProfileURL { get; set; }
        public string UserName { get; set; }
        public string Uid { get; set; }
        public string ProfilePicture { get; set; }
        public string Name { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string GroupName { get; set; }
        public string AdditionalData { get; set; }
        public string AimagName { get; set; }
        public string SumName { get; set; }
        public string Fname_UserName { get; set; }
        public string Lname_UserName { get; set; }
    }
}
