//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Account_More
    {
        public long UserID { get; set; }
        public string about { get; set; }
        public string address { get; set; }
        public string birthday { get; set; }
        public Nullable<int> age_range_min { get; set; }
        public Nullable<int> age_range_max { get; set; }
        public string first_name { get; set; }
        public string gender { get; set; }
        public string hometown_id { get; set; }
        public string hometown_name { get; set; }
        public long id { get; set; }
        public string email { get; set; }
        public string install_type { get; set; }
        public Nullable<bool> installed { get; set; }
        public string last_name { get; set; }
        public string link { get; set; }
        public string location_id { get; set; }
        public string location_name { get; set; }
        public string name { get; set; }
        public string name_format { get; set; }
        public string cover_link { get; set; }
    }
}
