//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Pages
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string ObjectID { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<bool> IsPrivateAccout { get; set; }
        public Nullable<bool> IsRealTimeMonitor { get; set; }
        public Nullable<bool> IsElectional { get; set; }
        public Nullable<bool> IsRemove { get; set; }
        public Nullable<bool> IsAds { get; set; }
        public string AccessToken { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> AimagID { get; set; }
        public Nullable<System.Guid> SumID { get; set; }
        public Nullable<bool> IsChecked { get; set; }
    }
}
