//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class News_Newspaper_New
    {
        public string Title { get; set; }
        public string NewsPaperUrl { get; set; }
        public string FullText { get; set; }
        public string PaperFullPicture { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public System.Guid ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
