//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Voters_Party
    {
        public System.Guid ID { get; set; }
        public string SureName { get; set; }
        public string Name { get; set; }
        public Nullable<double> Age { get; set; }
        public string Sex { get; set; }
        public string RegisterNumber { get; set; }
        public string Address { get; set; }
        public Nullable<double> RegionID_Float { get; set; }
        public Nullable<System.Guid> RegionID { get; set; }
        public string RegionName { get; set; }
        public Nullable<double> AimagID_Float { get; set; }
        public Nullable<System.Guid> AimagID { get; set; }
        public string AimagName { get; set; }
        public Nullable<double> SumDuuregID_Float { get; set; }
        public Nullable<System.Guid> SumDuuregID { get; set; }
        public string SumDuuregName { get; set; }
        public Nullable<double> BagKhorooID_Float { get; set; }
        public Nullable<System.Guid> BagKhorooID { get; set; }
        public string BagKhorooName { get; set; }
        public Nullable<double> Party { get; set; }
        public string FacebookName { get; set; }
        public string PhoneNumber { get; set; }
        public string Status { get; set; }
        public Nullable<System.Guid> JobID { get; set; }
        public Nullable<int> JobID_Float { get; set; }
        public string JobName { get; set; }
        public Nullable<System.Guid> JobCategoryID { get; set; }
        public Nullable<int> JobCategoryID_Float { get; set; }
        public string JobCategoryName { get; set; }
        public string FacebookID { get; set; }
        public string FacebookID1 { get; set; }
        public string FacebookID2 { get; set; }
        public string BirthAimag { get; set; }
        public string BirthSum { get; set; }
        public string AgeGroup { get; set; }
    }
}
