//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Candidates
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<bool> IsOwn { get; set; }
        public string PartyName { get; set; }
        public Nullable<int> SortOrder { get; set; }
    }
}
