//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_View
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> PersonID1 { get; set; }
        public Nullable<System.Guid> PersonID2 { get; set; }
        public Nullable<System.Guid> PersonID3 { get; set; }
        public Nullable<System.Guid> GroupID1 { get; set; }
        public Nullable<System.Guid> GroupID2 { get; set; }
        public Nullable<System.Guid> GroupID3 { get; set; }
    }
}
