//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Voters
    {
        public System.Guid ID { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public string SureName { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
        public string RegisterNumber { get; set; }
        public string Aimag { get; set; }
        public string Sum { get; set; }
        public string Address { get; set; }
        public string Party { get; set; }
        public string PartyTendence { get; set; }
        public string FacebookID { get; set; }
        public string PhoneNumber1 { get; set; }
        public string PhoneNumber2 { get; set; }
        public string PhoneNumber3 { get; set; }
        public string PhoneNumber4 { get; set; }
        public string PhoneNumber5 { get; set; }
        public string PhoneNumber6 { get; set; }
        public string PhoneNumber7 { get; set; }
        public string PhoneNumber8 { get; set; }
        public string PhoneNumber9 { get; set; }
        public string PhoneNumber10 { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string AimagGaral { get; set; }
        public string SumGaral { get; set; }
        public string Khoroo { get; set; }
        public string Email { get; set; }
        public string BirthdayHalf { get; set; }
        public string BirthdayFull { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public Nullable<bool> IsNew { get; set; }
    }
}
