//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Keys
    {
        public System.Guid ID { get; set; }
        public string Key1 { get; set; }
        public string Key2 { get; set; }
        public string Key3 { get; set; }
        public string Key4 { get; set; }
        public string Lattin1 { get; set; }
        public string Lattin2 { get; set; }
        public string Lattin3 { get; set; }
        public string Lattin4 { get; set; }
        public Nullable<System.Guid> KeyTypeID { get; set; }
        public Nullable<System.Guid> PersonID { get; set; }
        public Nullable<System.Guid> GroupID { get; set; }
        public Nullable<System.Guid> HoptopicID { get; set; }
    }
}
