//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Voters_Multiple
    {
        public System.Guid ID { get; set; }
        public string Registernumber { get; set; }
        public string ForeName { get; set; }
        public string SureName { get; set; }
        public string Name { get; set; }
        public string Sex { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string Address { get; set; }
        public string AimagCity { get; set; }
        public string SumDuureg { get; set; }
        public string BagKhoroo { get; set; }
        public string Street { get; set; }
        public string Apartment { get; set; }
        public string Door { get; set; }
        public string ElectionPlaceName { get; set; }
        public string AgeGroup { get; set; }
    }
}
