//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Twitter_Tweets
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TwitterUserID { get; set; }
        public string TweetID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public string ScreenName { get; set; }
        public string Source { get; set; }
        public string StatusID { get; set; }
        public Nullable<int> RetweetCount { get; set; }
        public Nullable<bool> Retweeted { get; set; }
        public string FullText { get; set; }
        public string Language { get; set; }
        public string Text { get; set; }
        public Nullable<bool> TrimUser { get; set; }
        public Nullable<bool> Truncated { get; set; }
        public Nullable<long> UserID { get; set; }
        public string HashEntity1 { get; set; }
        public string HashEntity2 { get; set; }
        public string HashEntity3 { get; set; }
        public string SymbolEntity1 { get; set; }
        public string SymbolEntity2 { get; set; }
        public string SymbolEntity3 { get; set; }
        public string UrlEntity1 { get; set; }
        public string UrlEntityDisplayUrl1 { get; set; }
        public string UrlEntityExpandedUrl1 { get; set; }
        public string UrlEntity2 { get; set; }
        public string UrlEntityDisplayUrl2 { get; set; }
        public string UrlEntityExpandedUrl2 { get; set; }
        public string UrlEntity3 { get; set; }
        public string UrlEntityDisplayUrl3 { get; set; }
        public string UrlEntityExpandedUrl3 { get; set; }
        public string MediaEntitiy1 { get; set; }
        public string MediaEntitiyDisplayUrl1 { get; set; }
        public string MediaEntitiyMediaUrl1 { get; set; }
        public string MediaEntitiyVideoInfo1 { get; set; }
        public string MediaEntity2 { get; set; }
        public string MediaEntitiyDisplayUrl2 { get; set; }
        public string MediaEntitiyMediaUrl2 { get; set; }
        public string MediaEntitiyVideoInfo2 { get; set; }
        public string MediaEntity3 { get; set; }
        public string MediaEntitiyDisplayUrl3 { get; set; }
        public string MediaEntitiyMediaUrl3 { get; set; }
        public string MediaEntitiyVideoInfo3 { get; set; }
        public string UserMentionEntity1 { get; set; }
        public string UserMentionEntityScreenName1 { get; set; }
        public string UserMentionEntity2 { get; set; }
        public string UserMentionEntityScreenName2 { get; set; }
        public string UserMentionEntity3 { get; set; }
        public string UserMentionEntityScreenName3 { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
        public string IsManual { get; set; }
        public string TwFullPicture { get; set; }
    }
}
