//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Twitter_Tweet_Person
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TweetID { get; set; }
        public Nullable<System.Guid> PersonID { get; set; }
        public string Sentiment { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
