//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenu
    {
        public System.Guid ID { get; set; }
        public string name { get; set; }
        public Nullable<System.Guid> parentID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<System.Guid> userID { get; set; }
        public Nullable<int> childMenu { get; set; }
    }
}
