//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSite_Banks_Posts_Comments
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PostID { get; set; }
        public string IP { get; set; }
        public string Name { get; set; }
        public string Text { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> LikeCount { get; set; }
        public Nullable<int> DisLikeCount { get; set; }
        public string Sentment { get; set; }
    }
}
