//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSite_Banks_Posts
    {
        public System.Guid ID { get; set; }
        public string BankName { get; set; }
        public string Link { get; set; }
        public string Reporter { get; set; }
        public string Title { get; set; }
        public Nullable<int> CommentCount { get; set; }
        public string Text { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Sentement { get; set; }
        public Nullable<int> ViewCount { get; set; }
        public Nullable<int> PostLike { get; set; }
        public Nullable<int> PostDisLike { get; set; }
    }
}
