//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebSites
    {
        public System.Guid ID { get; set; }
        public string SiteName { get; set; }
        public string Url { get; set; }
        public int Level { get; set; }
        public string SiteColorCode { get; set; }
        public string PostListTagID { get; set; }
        public string HtmlTagID { get; set; }
        public string TitleTagID { get; set; }
        public string CoverTagID { get; set; }
        public string BodyTagID { get; set; }
        public string DateTimeTagID { get; set; }
        public string ReporterTagID { get; set; }
        public string CommentTagID { get; set; }
        public string CommentInput { get; set; }
        public string CommentSubmit { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public byte[] Logo { get; set; }
        public Nullable<bool> isHiddenHTML { get; set; }
        public Nullable<bool> isContainComments { get; set; }
    }
}
