//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XBACKUP_Facebook_Posts_Backup
    {
        public System.Guid ID { get; set; }
        public string ParrentObjectID { get; set; }
        public Nullable<System.Guid> PageID { get; set; }
        public Nullable<System.Guid> GroupID { get; set; }
        public string ObjectID { get; set; }
        public string Link { get; set; }
        public string Text { get; set; }
        public string Story { get; set; }
        public Nullable<int> TotalReactionCount { get; set; }
        public Nullable<int> WowCount { get; set; }
        public Nullable<int> AngryCount { get; set; }
        public Nullable<int> SadCount { get; set; }
        public Nullable<int> YayCount { get; set; }
        public Nullable<int> HahaCount { get; set; }
        public Nullable<int> LoveCount { get; set; }
        public Nullable<int> LikesCount { get; set; }
        public Nullable<int> SharesCount { get; set; }
        public Nullable<System.DateTime> CheckedDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Sentiment { get; set; }
    }
}
