//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Twitter_User_Details
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TwitterUserID { get; set; }
        public Nullable<bool> ContributorsEnabled { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<long> Cursor { get; set; }
        public Nullable<bool> DefaultProfile { get; set; }
        public Nullable<bool> DefaultProfileImage { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }
        public Nullable<int> FavoritesCount { get; set; }
        public Nullable<bool> FollowRequestSent { get; set; }
        public Nullable<int> FollowersCount { get; set; }
        public Nullable<bool> Following { get; set; }
        public Nullable<int> FriendsCount { get; set; }
        public Nullable<bool> GeoEnabled { get; set; }
        public string ImageSize { get; set; }
        public Nullable<bool> IncludeEntities { get; set; }
        public Nullable<bool> IsTranslator { get; set; }
        public string Lang { get; set; }
        public string LangResponse { get; set; }
        public Nullable<int> ListedCount { get; set; }
        public string Location { get; set; }
        public string Name { get; set; }
        public Nullable<bool> Notifications { get; set; }
        public Nullable<int> Page { get; set; }
        public string ProfileBackgroundColor { get; set; }
        public string ProfileBackgroundImageUrl { get; set; }
        public string ProfileBackgroundImageUrlHttps { get; set; }
        public Nullable<bool> ProfileBackgroundTile { get; set; }
        public string ProfileBannerUrl { get; set; }
        public string ProfileImage { get; set; }
        public string ProfileImageUrl { get; set; }
        public string ProfileImageUrlHttps { get; set; }
        public string ProfileLinkColor { get; set; }
        public string ProfileSidebarBorderColor { get; set; }
        public string ProfileSidebarFillColor { get; set; }
        public string ProfileTextColor { get; set; }
        public Nullable<bool> ProfileUseBackgroundImage { get; set; }
        public Nullable<bool> Protected { get; set; }
        public string Query { get; set; }
        public string ScreenName { get; set; }
        public string ScreenNameList { get; set; }
        public string ScreenNameResponse { get; set; }
        public Nullable<bool> ShowAllInlineMedia { get; set; }
        public Nullable<bool> SkipStatus { get; set; }
        public string Slug { get; set; }
        public Nullable<int> StatusesCount { get; set; }
        public string TimeZone { get; set; }
        public string Type { get; set; }
        public string Url { get; set; }
        public Nullable<long> UserID { get; set; }
        public string UserIDResponse { get; set; }
        public string UserIdList { get; set; }
        public Nullable<int> UtcOffset { get; set; }
        public Nullable<bool> Verified { get; set; }
    }
}
