//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Phones
    {
        public long PhoneNo { get; set; }
        public string Url { get; set; }
        public string Html { get; set; }
        public bool IsChecked { get; set; }
        public Nullable<long> Id { get; set; }
        public string Username { get; set; }
        public string RegisterNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Update { get; set; }
        public string UpdateUserId { get; set; }
        public Nullable<int> UpdateRepeatIdx { get; set; }
    }
}
