//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Person
    {
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public string Surename { get; set; }
        public Nullable<System.Guid> GroupID { get; set; }
        public Nullable<System.Guid> FacebookPageID1 { get; set; }
        public Nullable<System.Guid> FacebookPageID2 { get; set; }
        public Nullable<System.Guid> FacebookPageID3 { get; set; }
        public Nullable<System.Guid> FacebookGroupID1 { get; set; }
        public Nullable<System.Guid> FacebookGroupID2 { get; set; }
        public Nullable<System.Guid> FacebookGroupID3 { get; set; }
        public Nullable<System.Guid> TwitterUserID1 { get; set; }
        public Nullable<System.Guid> TwitterUserID2 { get; set; }
        public Nullable<System.Guid> TwitterUserID3 { get; set; }
        public Nullable<System.Guid> WebSiteID1 { get; set; }
        public Nullable<System.Guid> WebSiteID2 { get; set; }
        public Nullable<System.Guid> WebSiteID3 { get; set; }
        public string Picture { get; set; }
        public string Description { get; set; }
        public string FacebookAccount { get; set; }
        public string TwitterAccount { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public Nullable<System.Guid> userID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> childMenu { get; set; }
        public string Tittlename { get; set; }
    }
}
