//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Bag
    {
        public System.Guid ID { get; set; }
        public string Bag { get; set; }
        public Nullable<System.Guid> SumID { get; set; }
        public Nullable<System.Guid> AimagID { get; set; }
    }
}
