//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class XBACKUP_System_Voters_Party
    {
        public System.Guid ID { get; set; }
        public string SureName { get; set; }
        public string Name { get; set; }
        public string Age { get; set; }
        public string RegisterNumber { get; set; }
        public string Address { get; set; }
        public Nullable<int> MaterialStatus { get; set; }
        public Nullable<int> PartyStatus { get; set; }
        public string Facebook_Display { get; set; }
        public string PhoneNumber { get; set; }
        public string Status { get; set; }
    }
}
