//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Post_Attachment
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> PostID { get; set; }
        public string MediaURL { get; set; }
        public string TargetID { get; set; }
        public string TargetURL { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string Url { get; set; }
        public string Description { get; set; }
    }
}
