//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_Report
    {
        public System.Guid ID { get; set; }
        public int SortOrder { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TeamName { get; set; }
        public string Report { get; set; }
    }
}
