//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Accounts
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string DisplayName { get; set; }
        public string CurrentCityName { get; set; }
        public string CurrentCityId { get; set; }
        public string HometownName { get; set; }
        public string HometownId { get; set; }
        public string Mobile { get; set; }
        public string Facebook { get; set; }
        public string Twitter { get; set; }
        public string Email { get; set; }
        public string Birthday { get; set; }
        public string Gender { get; set; }
        public string Job { get; set; }
        public string WorkName { get; set; }
        public string WorkUrl { get; set; }
        public string Profession { get; set; }
        public string UniversityName { get; set; }
        public string UniversityUrl { get; set; }
        public Nullable<bool> Checked { get; set; }
        public string UpdateOwnerUserName { get; set; }
        public Nullable<long> ProfileId { get; set; }
        public string PoliticalParty { get; set; }
        public string OperationDirection { get; set; }
        public string Sentiment { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string DTE { get; set; }
        public string PartyName { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string ProfileImage { get; set; }
        public string URL { get; set; }
        public string FName_Name { get; set; }
        public string LName_Name { get; set; }
        public string FName_UserName { get; set; }
        public string LName_UserName { get; set; }
        public string FName_Facebook { get; set; }
        public string LName_Facebook { get; set; }
        public string FName_Name_M { get; set; }
        public string LName_Name_M { get; set; }
        public string FName_UserName_M { get; set; }
        public string LName_UserName_M { get; set; }
        public string FName_Facebook_M { get; set; }
        public string LName_Facebook_M { get; set; }
    }
}
