//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class System_User
    {
        public System.Guid ID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public string SureName { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> KhorooID { get; set; }
        public Nullable<System.Guid> CandiateID { get; set; }
    }
}
