//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facebook_Post_Comments
    {
        public System.Guid ID { get; set; }
        public System.Guid PostID { get; set; }
        public string CommentID { get; set; }
        public string ObjectID { get; set; }
        public string FromID { get; set; }
        public string FromName { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> PositiveCount { get; set; }
        public Nullable<int> NegativeCount { get; set; }
        public string Sentiment { get; set; }
        public Nullable<bool> Sentiment_Confirmed { get; set; }
        public Nullable<bool> Question { get; set; }
        public Nullable<int> Likes { get; set; }
        public Nullable<System.DateTime> RegisteredDate { get; set; }
    }
}
