//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialMonster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopNewsForTopic
    {
        public System.Guid ID { get; set; }
        public Nullable<System.Guid> TopicID { get; set; }
        public string Type { get; set; }
        public string Title { get; set; }
        public string Source { get; set; }
        public string Date { get; set; }
        public Nullable<int> ViralCount { get; set; }
        public string Image { get; set; }
        public string Link { get; set; }
        public string SourceLink { get; set; }
        public string Text { get; set; }
        public string Profile { get; set; }
    }
}
